### PR TITLE
Search 2D matrix 

### LINKED ISSUE #173: 0074 - Search a 2D Matrix
## Description of the Problem
Write an efficient algorithm that searches for a value in an _m x n_ matrix. This matrix has the following properties:

- Integers in each row are sorted from left to right.
- The first integer of each row is greater than the last integer of the previous row.

**Example 1:**
```
Input:
matrix = [
  [1,   3,  5,  7],
  [10, 11, 16, 20],
  [23, 30, 34, 50]
]
target = 3
Output: true
```

**Example 2:**
```
Input:
matrix = [
  [1,   3,  5,  7],
  [10, 11, 16, 20],
  [23, 30, 34, 50]
]
target = 13
Output: false
```

## Code
```
class Solution:
    def searchMatrix(self, matrix: List[List[int]], target: int) -> bool:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/search-a-2d-matrix/)

### PR DESCRIPTION
**Pull request by ashvinimore**
**IMPORTANT: Please do not create a Pull Request without an issue.**

### All Submissions:

* [ ] I have read the CONTRIBUTING document.
* [ ] My code is written in **Python3** and is ending with _.py_
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] I have checked that my submission does pass the test on LeetCode.com 
* [ ] Does your filename follow the naming Conventions?
* [ ] Have you linked your PR to an Issue?

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by ashvinimore** [comment]
closes #173

**Comment by vJechsmayr** [comment]
@ashvinimore please do only commit .py file for this problem - not that much spam files!

**Comment by ashvinimore** [comment]
Sorry Mam. but I don't understand where did I go wrong..Sorry again

**Comment by ashvinimore** [comment]
Should I try one more time?

**Pull request closed without merging**
