### PR TITLE
Solution to 0054 Spiral Matrix

### LINKED ISSUE #161: 0054 - Spiral Matrix
## Description of the Problem
Given a matrix of _m x n_ elements (_m_ rows, _n_ columns), return all elements of the matrix in spiral order.

**Example 1:**
```
Input:
[
 [ 1, 2, 3 ],
 [ 4, 5, 6 ],
 [ 7, 8, 9 ]
]
Output: [1,2,3,6,9,8,7,4,5]
```

**Example 2:**
```
Input:
[
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9,10,11,12]
]
Output: [1,2,3,4,8,12,11,10,9,5,6,7]
```

## Code
```
class Solution:
    def spiralOrder(self, matrix: List[List[int]]) -> List[int]:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/spiral-matrix/)

### LINKED ISSUE #181: 0042 - Trapping Rain Water
## Description of the Problem
Given _n_ non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it is able to trap after raining.

image
_The above elevation map is represented by array [0,1,0,2,1,0,1,3,2,1,2,1]. In this case, 6 units of rain water (blue section) are being trapped. Thanks Marcos for contributing this image!_

**Example:**
```
Input: [0,1,0,2,1,0,1,3,2,1,2,1]
Output: 6
```

## Code
```
class Solution:
    def trap(self, height: List[int]) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/trapping-rain-water/)

### PR DESCRIPTION
**Pull request by divyhshah**
**IMPORTANT: Please do not create a Pull Request without an issue.**

### All Submissions:

* [x] I have read the CONTRIBUTING document.
* [x] My code is written in **Python3** and is ending with _.py_
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] I have checked that my submission does pass the test on LeetCode.com 
* [x] Does your filename follow the naming Conventions?
* [x] Have you linked your PR to an Issue?

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by divyhshah** [comment]
Hey @vJechsmayr  can you please approve this

**Comment by divyhshah** [comment]
closes #177

**Comment by vJechsmayr** [comment]
@divyhshah NO Issue linked! please replace XXXX with the Issue number!

**Comment by divyhshah** [comment]
> @divyhshah NO Issue linked! please replace XXXX with the Issue number!

Sure!

**Review by vJechsmayr — APPROVED** [review]
Thank you for contributing to my #hacktoberfest Repository!
Happy Hacktoberfest!

**Comment by divyhshah** [comment]
> Thank you for contributing to my #hacktoberfest Repository!
> Happy Hacktoberfest!

Thank you @vJechsmayr

**Comment by divyhshah** [comment]
> > Thank you for contributing to my #hacktoberfest Repository!
> > Happy Hacktoberfest!
> 
> Thank you @vJechsmayr but i don't know why hacktoberfest still showing it as pending

**Pull request merged**
