### PR TITLE
111_Median_of_two_sorted_array

### PR DESCRIPTION
**Pull request by Himsahu**
**IMPORTANT: Please do not create a Pull Request without an issue.**

### All Submissions:

* [ ] I have read the CONTRIBUTING document.
* [ ] My code is written in **Python3** and is ending with _.py_
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] I have checked that my submission does pass the test on LeetCode.com 
* [ ] Does your filename follow the naming Conventions?
* [ ] Have you linked your PR to an Issue?

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Review by riwim — CHANGES_REQUESTED** [review]
Thanks for your contribution ✨

Please
* Re-check "My code is written in Python3 and is ending with .py"
* Re-check "Have you linked your PR to an Issue?"

**Comment by Himsahu** [comment]
I have pushed my code to complete my hacktoberfest task

**Comment by Himsahu** [comment]
Is there anything wrong in my PR

**Comment by riwim** [comment]
Yes. You still need to

1. Add `.py` to the filename of your solution and
1. Link your PR with an issue

Check CONTRIBUTING.md for details on both points.

**Comment by Himsahu** [comment]
Done with the changes

**Comment by riwim** [comment]
You still haven't linked this PR with an open issue. But after renaming the file to `0004_...` it becomes clear that you are trying to solve a problem that was already solved in #4. Please read
<https://github.com/vJechsmayr/PythonAlgorithms#opening-issues> and submit only solutions to unsolved problems with open issues to avoid your PR being rejected.

**Comment by Himsahu** [comment]
OK leave that PR I got you. The problem is solved by any other guy. I have requested you another PR named water_glass.py please confirm my code.

**Comment by riwim** [comment]
Sure. Please close this PR so that the maintainer does not have to review this discussion and PR.
[Closing a PR](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/closing-a-pull-request)

**Pull request closed without merging**
