### PR TITLE
Created a power function which finishes in O(Log(n)) time

### PR DESCRIPTION
**Pull request by cscipher**
**IMPORTANT: Please do not create a Pull Request without an issue.**

### All Submissions:

* [x] I have read the CONTRIBUTING document.
* [x] My code is written in **Python3** and is ending with _.py_
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] I have checked that my submission does pass the test on LeetCode.com 
* [x] Does your filename follow the naming Conventions?
* [ ] Have you linked your PR to an Issue?

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by cscipher** [comment]
Proof : [SS to leetCode Soln.](https://drive.google.com/file/d/1NbmQb0sA2seDpkpxiIafES1sXJWVplCU/view?usp=sharing)

**Comment by vJechsmayr** [comment]
Issue/Problem already solved - closed as spam

**Comment by cscipher** [comment]
Already solved? when?

**Comment by cscipher** [comment]
I solved it the same day man!

**Pull request closed without merging**
