### PR TITLE
Created simplify path.py

### LINKED ISSUE #171: 0071 - Simplify Path
## Description of the Problem
Given an **absolute path** for a file (Unix-style), simplify it. Or in other words, convert it to the **canonical path**.

In a UNIX-style file system, a period `.` refers to the current directory. Furthermore, a double period `..` moves the directory up a level.

Note that the returned canonical path must always begin with a slash `/`, and there must be only a single slash `/` between two directory names. The last directory name (if it exists) **must not** end with a trailing `/`. Also, the canonical path must be the **shortest** string representing the absolute path.

**Example 1:**
```
Input: "/home/"
Output: "/home"
Explanation: Note that there is no trailing slash after the last directory name.
```

**Example 2:**
```
Input: "/../"
Output: "/"
Explanation: Going one level up from the root directory is a no-op, as the root level is the highest level you can go.
```

**Example 3:**
```
Input: "/home//foo/"
Output: "/home/foo"
Explanation: In the canonical path, multiple consecutive slashes are replaced by a single one.
```

**Example 4:**
```
Input: "/a/./b/../../c/"
Output: "/c"
```

**Example 5:**
```
Input: "/a/../../b/../c//.//"
Output: "/c"
```

**Example 6:**
```
Input: "/a//b////c/d//././/.."
Output: "/a/b/c"
```

## Code
```
class Solution:
    def simplifyPath(self, path: str) -> str:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/simplify-path/)

### PR DESCRIPTION
**Pull request by rakshaa2000**
#171 
**IMPORTANT: Please do not create a Pull Request without an issue.**
closes #171 

### All Submissions:

* [x] I have read the CONTRIBUTING document.
* [x] My code is written in **Python3** and is ending with _.py_
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] I have checked that my submission does pass the test on LeetCode.com 
* [x] Does your filename follow the naming Conventions?
* [x] Have you linked your PR to an Issue?

**Closing issues**

Put `closes #171 ` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Review by aekt — COMMENTED** [review]
Hi @rakshaa2000 could you link to #171 correctly? Also, your filename is not follow the naming convention

**Comment by rakshaa2000** [comment]
Cool, I'll change it.

**Comment by rakshaa2000** [comment]
I have changed it and linked the issue as well. Please verify.

**Review by vJechsmayr — APPROVED** [review]
Thanks for contributing - Merged!

Runtime: 56 ms

Happy Hacktoberfest!

**Comment by vJechsmayr** [comment]
@aekt Thanks for having a look too 😃

**Pull request merged**
