### PR TITLE
0076_Minimum_Window_Substring 

### LINKED ISSUE #175: 0076 - Minimum Window Substring
## Description of the Problem
Given a string S and a string T, find the minimum window in S which will contain all the characters in T in complexity O(n).

**Example:**
```
Input: S = "ADOBECODEBANC", T = "ABC"
Output: "BANC"
```

**Note:**
- If there is no such window in S that covers all characters in T, return the empty string `""`.
- If there is such window, you are guaranteed that there will always be only one unique minimum window in S.

## Code
```
class Solution:
    def minWindow(self, s: str, t: str) -> str:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/minimum-window-substring/)

### PR DESCRIPTION
**Pull request by suparna13**
**IMPORTANT: Please do not create a Pull Request without an issue.**
closes #175 

### All Submissions:

* [x] I have read the CONTRIBUTING document.
* [x] My code is written in **Python3** and is ending with _.py_
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] I have checked that my submission does pass the test on LeetCode.com 
* [x] Does your filename follow the naming Conventions?
* [x] Have you linked your PR to an Issue?

**Closing issues**

Put `closes #175  ` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by suparna13** [comment]
@vJechsmayr Can you please take a look at PR?

**Review by vJechsmayr — CHANGES_REQUESTED** [review]
pattern at Line 6 is not defined - please check again

**Comment by suparna13** [comment]
@vJechsmayr I have updated code as per requested changes. Please take a look at once. Thank you.

**Review by vJechsmayr — APPROVED** [review]
@suparna13 Looks good now! Thanks for changing & Thanks for contributing - Merged!

Runtime: 92 ms

Happy Hacktoberfest!

**Pull request merged**
