### PR TITLE
count digit one added

### LINKED ISSUE #151: 0233 - Number of Digit One
## Description of the Problem
Given an integer n, count the total number of digit 1 appearing in all non-negative integers less than or equal to n.

**Example:**
```
Input: 13
Output: 6 
Explanation: Digit 1 occurred in the following numbers: 1, 10, 11, 12, 13.
```

## Code
```
class Solution:
    def countDigitOne(self, n: int) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/number-of-digit-one/)

### PR DESCRIPTION
**Pull request by sourabmaity**
**IMPORTANT: Please do not create a Pull Request without an issue.**

### All Submissions:

* [x] I have read the CONTRIBUTING document.
* [x] My code is written in **Python3** and is ending with _.py_
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] I have checked that my submission does pass the test on LeetCode.com 
* [x] Does your filename follow the naming Conventions?
* [x] Have you linked your PR to an Issue?

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by vJechsmayr** [comment]
@SOURAB-BAPPA no issue linked

**Comment by sourabmaity** [comment]
issue no#151

**Comment by sourabmaity** [comment]
sorry for that

**Review by vJechsmayr — CHANGES_REQUESTED** [review]
@SOURAB-BAPPA Code does not pass test on Leetcode - please check it again

**Comment by sourabmaity** [comment]
sorry sir but this program properly run in pycharm, VSCode, programiz(online compiler), and also LeetCode
image

**Comment by SOURAB-BAPPA** [comment]
Leetcode(online compiler) fail to take the input .

**Comment by SOURAB-BAPPA** [comment]
How to take input in LeetCode in python 3 ?
input() is not working in leetCode

**Comment by sourabmaity** [comment]
so sir another PR is required or not?

**Comment by vJechsmayr** [comment]
@SOURAB-BAPPA Code Test on LeetCode get's a TimeOut - please test it on leetcode yourself to be sure it works

**Comment by vJechsmayr** [comment]
merged code by Dhanshu

**Pull request closed without merging**
