### PR TITLE
Create 1589-maximum-sum-obtained-of-any-permutation.py

### LINKED ISSUE #553: 1589 - Maximum Sum Obtained of Any Permutation
## Description of the Problem
We have an array of integers, nums, and an array of requests where requests[i] = [starti, endi]. The ith request asks for the sum of nums[starti] + nums[starti + 1] + ... + nums[endi - 1] + nums[endi]. Both starti and endi are 0-indexed.

Return the maximum total sum of all requests among all permutations of nums.

Since the answer may be too large, return it modulo 109 + 7.

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/maximum-sum-obtained-of-any-permutation/)

### PR DESCRIPTION
**Pull request by bhawesh96**
**IMPORTANT: Please do not create a Pull Request without an issue.**

### All Submissions:

* [x] I have read the CONTRIBUTING document.
* [x] My code is written in **Python3** and is ending with _.py_
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] I have checked that my submission does pass the test on LeetCode.com 
* [x] Does your filename follow the naming Conventions?
* [x] Have you linked your PR to an Issue?

closes #553

### CODE REVIEW

**Comment by bhawesh96** [comment]
@vJechsmayr , requesting you to kindly review this PR. Thanks

**Review by vJechsmayr — CHANGES_REQUESTED** [review]
Code does not pass Test on LeetCode - Please check again.

image

**Comment by bhawesh96** [comment]
@vJechsmayr , I've modified for Python3. Requesting a review again. Thanks

**Review by vJechsmayr — APPROVED** [review]
Thanks for contributing - Merged!

Runtime: 1652 ms

Happy Hacktoberfest!

**Pull request merged**
