### PR TITLE
Feature/1661_number_prime

### LINKED ISSUE #713: 1661 - Check if a number is prime
## Code
```
Input: 7
Output: 7 is  a prime number

Input: 8
Output: 8 is not a prime number
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/playground/U27rDXz6)

### PR DESCRIPTION
**Pull request by morenocl**
**IMPORTANT: Please do not create a Pull Request without an issue.**

### All Submissions:

* [x] I have read the CONTRIBUTING document.
* [x] My code is written in **Python3** and is ending with _.py_
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] I have checked that my submission does pass the test on LeetCode.com 
* [x] Does your filename follow the naming Conventions?
* [x] Have you linked your PR to an Issue?

**Closing issues**

Put `closes #0713` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by morenocl** [comment]
closes #0713

**Comment by riwim** [comment]
> closes #713

You want to put this in your first comment to really link the issue to this PR.

**Comment by morenocl** [comment]
> > closes #713
> 
> You want to put this in your first comment to really link the issue to this PR.

How do this?

**Comment by riwim** [comment]
- click on the three dots next to your first comment
- choose "edit"
- update the last line accordingly

**Pull request closed without merging**
