### PR TITLE
Add 1499. Max Value of Equation

### LINKED ISSUE #530: 1499 - Max Value of Equation
## Description of the Problem
Given an array points containing the coordinates of points on a 2D plane, sorted by the x-values, where `points[i] = [x_i, y_i]` such that `x_i < x_j` for all `1 <= i < j <= points.length`. You are also given an integer `k`.

Find the maximum value of the equation `y_i + y_j + |x_i - x_j|` where `|x_i - x_j| <= k` and `1 <= i < j <= points.length`. It is guaranteed that there exists at least one pair of points that satisfy the constraint `|x_i - x_j| <= k`.

## Code
```
class Solution(object):
    def findMaxValueOfEquation(self, points, k):
        """
        :type points: List[List[int]]
        :type k: int
        :rtype: int
        """
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/max-value-of-equation/)

### PR DESCRIPTION
**Pull request by livace**
**IMPORTANT: Please do not create a Pull Request without an issue.**

### All Submissions:

* [x] I have read the CONTRIBUTING document.
* [x] My code is written in **Python3** and is ending with _.py_
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] I have checked that my submission does pass the test on LeetCode.com 
* [x] Does your filename follow the naming Conventions?
* [x] Have you linked your PR to an Issue?

**Closing issues**

closes #530

### CODE REVIEW

**Review by vJechsmayr — CHANGES_REQUESTED** [review]
Please Check Code again.
Code does not pass the Test on [LeetCode](https://leetcode.com/problems/max-value-of-equation/)

**Comment by livace** [comment]
That's interesting. I have checked it 3 times in a row and it always passes tests
image

**Comment by vJechsmayr** [comment]
> That's interesting. I have checked it 3 times in a row and it always passes tests
> image

I see - you implemented it with Python - I checked it on Python3

**Comment by vJechsmayr** [comment]
Merged it 😸 

Runtime: 1296 ms

Happy Hacktoberfest!

**Pull request merged**
