### PR TITLE
solution for issues 0777(#143) , 1227(#144), 0933(#147), 0111(#149)

### PR DESCRIPTION
**Pull request by TanayKulkarni**
**IMPORTANT: Please do not create a Pull Request without an issue.**

### All Submissions:

* [x] I have read the CONTRIBUTING document.
* [x] My code is written in **Python3** and is ending with _.py_
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] I have checked that my submission does pass the test on LeetCode.com 
* [x] Does your filename follow the naming Conventions?
* [x] Have you linked your PR to an Issue?

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by TanayKulkarni** [comment]
Also have added for issue 0933, which had been assigned to me

**Comment by TanayKulkarni** [comment]
Have added the solutions to issues 1227 and 0111 as well! Happy Hacktoberfest!

**Comment by vJechsmayr** [comment]
@TanayKulkarni Make sure to link a Issue with the # hashtag or on the right side with **Linked Issues** Otherwise I always have to search what your issue is.

**Comment by TanayKulkarni** [comment]
Hey did you get the reference to the issues?

**Review by vJechsmayr — APPROVED** [review]
@TanayKulkarni Thank you for contributing to my #hacktoberfest Repository!
Happy Hacktoberfest!

**Pull request merged**
