### PR TITLE
Solution added for #1470 Shuffle The Array

### LINKED ISSUE #739: 1470 - Shuffle the Array
## Description of the Problem
Given the array nums consisting of 2n elements in the form [x1,x2,...,xn,y1,y2,...,yn].

Return the array in the form [x1,y1,x2,y2,...,xn,yn].

## Code
```
class Solution:
    def shuffle(self, nums: List[int], n: int) -> List[int]:
        shuffled_list = [0]*(2*n)
        left_index = 0
        right_index = n
        for index in range(0, 2*n):
            if index%2 == 0:
                shuffled_list[index] = nums[left_index]
                left_index += 1
            else:
                shuffled_list[index] = nums[right_index]
                right_index += 1
        return shuffled_list
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/shuffle-the-array/)

### PR DESCRIPTION
**Pull request by suhridmathur**
**IMPORTANT: Please do not create a Pull Request without an issue.**

### All Submissions:

* [x] I have read the CONTRIBUTING document.
* [x] My code is written in **Python3** and is ending with _.py_
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] I have checked that my submission does pass the test on LeetCode.com 
* [x] Does your filename follow the naming Conventions?
* [x] Have you linked your PR to an Issue?

**Closing issues**

closes #739

### CODE REVIEW

**Review by riwim — CHANGES_REQUESTED** [review]
Please re-check:
"My code is written in Python3 and is ending with .py"

**Comment by riwim** [comment]
Duplicate of #587

**Comment by suhridmathur** [comment]
I didn't notice that, since the pull request wasn't merged and this problem wasn't present in master branch.

**Review by vJechsmayr — APPROVED** [review]
Thanks for contributing - Merged!

Runtime:60 ms 

Happy Hacktoberfest!

**Pull request merged**
