### PR TITLE
0292_Nim_Game

### LINKED ISSUE #132: 0292 - Nim Game
## Description of the Problem
You are playing the following Nim Game with your friend: There is a heap of stones on the table, each time one of you take turns to remove 1 to 3 stones. The one who removes the last stone will be the winner. You will take the first turn to remove the stones.

Both of you are very clever and have optimal strategies for the game. Write a function to determine whether you can win the game given the number of stones in the heap.

**Example 1:**
```
Input: n = 4
Output: false
Explanation: If there are 4 stones in the heap, then you will never win the game;
No matter 1, 2, or 3 stones you remove, the last stone will always be removed by your friend.
```

**Example 2:**
```
Input: n = 1
Output: true
```

**Example 3:**
```
Input: n = 2
Output: true
```

**Constraints:**
- `1 <= n <= 231 - 1`

## Code
```
class Solution:
    def canWinNim(self, n: int) -> bool:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/nim-game/)

### PR DESCRIPTION
**Pull request by sarthak55k**
**IMPORTANT: Please do not create a Pull Request without an issue.**

### All Submissions:

* [x] I have read the CONTRIBUTING document.
* [x] My code is written in **Python3** and is ending with _.py_
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] I have checked that my submission does pass the test on LeetCode.com 
* [x] Does your filename follow the naming Conventions?
* [x] Have you linked your PR to an Issue?

**Closing issues**

Put `closes #132 ` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by vJechsmayr** [comment]
@sarthak55k No issue linked

**Comment by sarthak55k** [comment]
#132

**Comment by sarthak55k** [comment]
close #132

**Comment by sarthak55k** [comment]
closes #132

**Review by vJechsmayr — APPROVED** [review]
Thanks for contributing - Merged!

Runtime: 36 ms

Happy Hacktoberfest!

**Pull request merged**
