### PR TITLE
Add the solution for "0383 - Ransom Note" problem

### PR DESCRIPTION
**Pull request by GiorgiBeriashvili**
**IMPORTANT: Please do not create a Pull Request without an issue.**

### All Submissions:

* [x] I have read the CONTRIBUTING document.
* [x] My code is written in **Python3** and is ending with _.py_
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] I have checked that my submission does pass the test on LeetCode.com 
* [x] Does your filename follow the naming Conventions?
* [x] Have you linked your PR to an Issue?

**Closing issues**

Resolves the following issue: #264

### CODE REVIEW

**Review by vJechsmayr — COMMENTED** [review]
Please check your Algorithm once more - there is a Problem with one of the Testcases on Leetcode:
image

[https://leetcode.com/problems/ransom-note/submissions/](https://leetcode.com/problems/ransom-note/submissions/)

**Review by vJechsmayr — CHANGES_REQUESTED** [review]
see comment above

**Comment by GiorgiBeriashvili** [comment]
Curious... I will make adjustments right away!

**Comment by GiorgiBeriashvili** [comment]
I changed the faulty solution in order to work on the failed testcase and maybe improved its tangibility.

I also hopefully didn't mess anything up by committing again, it was my first time doing something like this. :sweat_smile:

**Review by vJechsmayr — APPROVED** [review]
Looks good now! 😸  Thanks for contributing - Merged!

Runtime: 36 ms

Happy Hacktoberfest!

**Pull request merged**
