### PR TITLE
0371_Sum of two integers 

### LINKED ISSUE #695: 0371 - Sum of Two Integers
## Description of the Problem
Calculate the sum of two integers a and b, but you are not allowed to use the operator + and -.

## Code
```
class Solution:
    def getSum(self, a: int, b: int) -> int:
        
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/sum-of-two-integers/)

### PR DESCRIPTION
**Pull request by uddeshyatyagi**
IMPORTANT: Please do not create a Pull Request without an issue.

All Submissions:
 I have read the CONTRIBUTING document.
 My code is written in Python3 and is ending with .py
 Have you checked to ensure there aren't other open Pull Requests for the same update/change?
 I have checked that my submission does pass the test on LeetCode.com
 Does your filename follow the naming Conventions?
 Have you linked your PR to an Issue?
Closing issues

Put closes #XXXX in your comment to auto-close the issue that your PR fixes (if such).

closes #695

### CODE REVIEW

**Review by uddeshyatyagi — COMMENTED** [review]
Hey! @vJechsmayr,please review and merge my pull request if you find that correct

**Review by riwim — CHANGES_REQUESTED** [review]
Thanks for your contribution ✨

Please re-check: "Have you linked your PR to an Issue?"

**Comment by uddeshyatyagi** [comment]
closes #0371

**Comment by uddeshyatyagi** [comment]
closes #708

**Comment by uddeshyatyagi** [comment]
i already linked it using #0371

**Comment by uddeshyatyagi** [comment]
i already refrenced it to the issue in my PR!?

**Comment by riwim** [comment]
The problem is:
* "371" is the number of the leetcode problem
* #708 is this pull request

In fact you need to need to create or find out the number of the existing **issue** and link it here. Please read the CONTRIBUTING.md for details on this point.

When you successfully linked a corresponding issue you will see it here in the right column.

**Comment by uddeshyatyagi** [comment]
`closes #708 `

**Comment by uddeshyatyagi** [comment]
closes #695

**Comment by uddeshyatyagi** [comment]
hey i have tried linking my PR to issue by:
1. using `closes #695 `
2. using closes #695 
3. using #695 in my PR 
but still i am not getting my PR linked to issue

**Comment by uddeshyatyagi** [comment]
fixes #695

**Comment by uddeshyatyagi** [comment]
Hey @riwim ,I have linked my PR to the issue,please review

**Comment by riwim** [comment]
LGTM now 👍 
Just a small remark: I wouldn't put a reference to an issue in the title of the PR. It's not totally wrong but still confusing.

**Comment by uddeshyatyagi** [comment]
> LGTM now 
> Just a small remark: I wouldn't put a reference to an issue in the title of the PR. It's not totally wrong but still confusing.

@riwim its removed now!!!

**Comment by vJechsmayr** [comment]
Not assigned to the linked issue - please consider Contributing Guidelines

**Pull request closed without merging**
