### PR TITLE
Proposed solution to problem 0032

### LINKED ISSUE #67: 0032 - Longest Valid Parentheses
## Description of the Problem
Given a string containing just the characters `'('` and `')'`, find the length of the longest valid (well-formed) parentheses substring.

**Example 1:**
```
Input: "(()"
Output: 2
Explanation: The longest valid parentheses substring is "()"
```

**Example 2:**
```
Input: ")()())"
Output: 4
Explanation: The longest valid parentheses substring is "()()"
```

## Code
```
class Solution:
    def longestValidParentheses(self, s: str) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/longest-valid-parentheses/)

### PR DESCRIPTION
**Pull request by aewens**
In regards to #67

### CODE REVIEW

**Review by vJechsmayr — CHANGES_REQUESTED** [review]
Wrong Testcase on LeetCode:
**Input**
`"(())()(()(("`
**Output**
`8`
**Expected**
`6`

You may check your code - and submit it again

**Comment by aewens** [comment]
I'll try to fix this, sorry about that!

**Comment by aewens** [comment]
@vJechsmayr: _Should_ be fixed now. If not please let me know and I can take another try and solving this one.

**Review by vJechsmayr — APPROVED** [review]
@aewens Looks good now! Thanks for fixing!
Thanks for contributing - Merged!

Runtime: 40 ms

Happy Hacktoberfest!

**Pull request merged**
