### PR TITLE
997_Find_The_Town_Judge.py

### LINKED ISSUE #758: 0997- Find the Town Judge
## Description of the Problem
In a town, there are N people labelled from 1 to N.  There is a rumor that one of these people is secretly the town judge.

If the town judge exists, then:

The town judge trusts nobody.
Everybody (except for the town judge) trusts the town judge.
There is exactly one person that satisfies properties 1 and 2.
You are given trust, an array of pairs trust[i] = [a, b] representing that the person labelled a trusts the person labelled b.

If the town judge exists and can be identified, return the label of the town judge.  Otherwise, return -1.

## Code
```
class Solution:
    def findJudge(self, N: int, trust: List[List[int]]) -> int:
        m=len(trust)
        if 1==N:
            if 0==m:
                return 1
        tmp={}
        dic={}
        for i in range(m):
            tmp[trust[i][0]]=1
        for i in range(m):
            if trust[i][1] not in tmp:
                if trust[i][1] not in dic:
                    dic[trust[i][1]]=1
                else:
                    dic[trust[i][1]]+=1
        for key in dic:
            if N-1==dic[key]:
                return key
        return -1
                

```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/find-the-town-judge/)

### PR DESCRIPTION
**Pull request by aman1833**
**IMPORTANT: Please do not create a Pull Request without an issue.**

### All Submissions:

* [x] I have read the CONTRIBUTING document.
* [x] My code is written in **Python3** and is ending with _.py_
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] I have checked that my submission does pass the test on LeetCode.com 
* [x] Does your filename follow the naming Conventions?
* [x] Have you linked your PR to an Issue?

**Closing issues**

Put closes #758   in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Review by riwim — CHANGES_REQUESTED** [review]
Thanks for your contribution ✨

Please fix:

* you provided more than one py file
* your submission does not pass the test on LeetCode.com

**Comment by aman1833** [comment]
updated my code with perfect solution

**Review by riwim — CHANGES_REQUESTED** [review]
Great, code LGTM! ✨ 

Now **open an issue** for this problem and link to the issue in this PR. Check CONTRIBUTING.md for details.

**Comment by aman1833** [comment]
> Great, code LGTM! ✨
> 
> Now **open an issue** for this problem and link to the issue in this PR. Check CONTRIBUTING.md for details.

done bro i raised an issue for this problem can you check if i have to do anything else

**Comment by riwim** [comment]
You are getting closer. You still have to **link your issue here**.

To do that: Just replace `XXXX` in the last line of your first comment with the number of your opened issue. Be sure to also remove the backticks around `closes #XXXX` so GitHub can recognize your issue link properly.
If everything went well, you can see your issue here in the right column.

**Comment by aman1833** [comment]
> You are getting closer. You still have to **link your issue here**.
> 
> To do that: Just replace `XXXX` in the last line of your first comment with the number of your opened issue. Be sure to also remove the backticks around `closes #XXXX` so GitHub can recognize your issue link properly.
> If everything went well, you can see your issue here in the right column.

how to check number of opened issue?

**Comment by riwim** [comment]
Use the search feature and search for "judge" in this repository to find your own issue. You'll find the issue id in parenthesis after the title.

**Comment by aman1833** [comment]
> Use the search feature and search for "judge" in this repository to find your own issue. You'll find the issue id in parenthesis after the title.

i made changes is right of i have to put # in that

**Comment by riwim** [comment]
Still two mistakes:

1. You took the wrong search result:
  image
  Don't take the id of (your) PR. Take the id of your issue.
2. You still forgot to put "closes" before the id.

**Comment by aman1833** [comment]
> Still two mistakes:
> 
> 1. You took the wrong search result:
>    image
>    Don't take the id of (your) PR. Take the id of your issue.
> 2. You still forgot to put "closes" before the id.

i think now everything is fine

**Comment by riwim** [comment]
Looks good to me now 👍

**Comment by aman1833** [comment]
> Looks good to me now 👍

Thanks bro

**Comment by aman1833** [comment]
> Looks good to me now 👍

pull request is still not accepted?

**Review by vJechsmayr — APPROVED** [review]
Thanks for contributing - Merged!

Runtime: 684 ms

Happy Hacktoberfest!

**Pull request merged**
