### PR TITLE
Added 3sum

### LINKED ISSUE #26: 0081 - Search in Rotated Sorted Array II
## Description of the Problem
Suppose an array sorted in ascending order is rotated at some pivot unknown to you beforehand.

(i.e., `[0,0,1,2,2,5,6]` might become `[2,5,6,0,0,1,2]`).

You are given a target value to search. If found in the array return true, otherwise return `false`.

**Example 1:**
```
Input: nums = [2,5,6,0,0,1,2], target = 0
Output: true

```
**Example 2:**
```
Input: nums = [2,5,6,0,0,1,2], target = 3
Output: false
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/search-in-rotated-sorted-array-ii/)

## Code
```
class Solution:
    def search(self, nums: List[int], target: int) -> bool:
        
```

### PR DESCRIPTION
**Pull request by VaibhaveS**
Added 3 problems

### CODE REVIEW

**Review by vJechsmayr — CHANGES_REQUESTED** [review]
Runtime Error at file 0043 and file 0081 - you may fix that 🛠️

**Comment by VaibhaveS** [comment]
@vJechsmayr Hello, the codes are working perfectly fine. If you want to run them on leetcode you must paste the code without disturbing the class solution.

**Comment by vJechsmayr** [comment]
@VaibhaveS  The class Solution is there as you can see 😃 

image

**Comment by VaibhaveS** [comment]
Hey, yeah it's due to indentation error while copy pasting, I checked the code the indentation is perfect...

**Pull request merged**
