### PR TITLE
Python programs

### PR DESCRIPTION
**Pull request by vikasjoshis001**
**IMPORTANT: Please do not create a Pull Request without an issue.**

### All Submissions:

* [x] I have read the CONTRIBUTING document.
* [x] My code is written in **Python3** and is ending with _.py_
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] I have checked that my submission does pass the test on LeetCode.com 
* [x] Does your filename follow the naming Conventions?
* [x] Have you linked your PR to an Issue?

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Review by riwim — CHANGES_REQUESTED** [review]
Please,

* read the CONTRIBUTING document
* link your PR to an Issue
* provide only one py file

**Comment by vikasjoshis001** [comment]
i have contributed some of my python programs.

**Review by riwim — CHANGES_REQUESTED** [review]
And we appreciate your contribution ✨
Please include **only one** solution per pull request **and** link the corresponding issue (create the issue if you haven't done yet) in this PR.

**Comment by vJechsmayr** [comment]
PR does not follow Contribution Guidelines - closed as **spam** 
No Issue linked

**Pull request closed without merging**
