### PR TITLE
closes issue #756 Count Complete tree nodes

### LINKED ISSUE #756: 0222 - Count Complete Tree Nodes
## Description of the Problem
Given a complete binary tree, count the number of nodes.

Note:

Definition of a complete binary tree from Wikipedia:
In a complete binary tree every level, except possibly the last, is completely filled, and all nodes in the last level are as far left as possible. It can have between 1 and 2h nodes inclusive at the last level h.

Example:

Input: 
    1
   / \
  2   3
 / \  /
4  5 6

Output: 6

## Code
```
# Definition for a binary tree node.
# class TreeNode:
#     def __init__(self, val=0, left=None, right=None):
#         self.val = val
#         self.left = left
#         self.right = right
class Solution:
    def countNodes(self, root: TreeNode) -> int:
```

## Link To The LeetCode Problem
[LeetCode](https://leetcode.com/problems/count-complete-tree-nodes/)

### PR DESCRIPTION
**Pull request by Ahkam95**
**IMPORTANT: Please do not create a Pull Request without an issue.**

### All Submissions:

* [x] I have read the CONTRIBUTING document.
* [x] My code is written in **Python3** and is ending with _.py_
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] I have checked that my submission does pass the test on LeetCode.com 
* [x] Does your filename follow the naming Conventions?
* [x] Have you linked your PR to an Issue?

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

closes #756

### CODE REVIEW

**Review by riwim — CHANGES_REQUESTED** [review]
Add `closes #756` (without backticks) to your comment to really link your issue. You can check here in the right column if you linked it correctly.

**Comment by Ahkam95** [comment]
@riwim  Thanks brother

**Comment by riwim** [comment]
Your are welcome.

LGTM now! 👍

**Review by vJechsmayr — APPROVED** [review]
Thanks for contributing - Merged!

Runtime: 72 ms

Happy Hacktoberfest!

**Pull request merged**
